### ISSUE TITLE
Just a syntax correction

### ISSUE THREAD

**Issue by wldhg** [Leward/mermaid-docsify#14]
Hi, I've found your plugin yesterday and now am using this very well. Thank you for your contribution.

Adding `</script>` to the [README](README.md) will make the README nicer.

```html
  <script src="//unpkg.com/docsify-mermaid@latest/dist/docsify-mermaid.js">
```

```html
  <script src="//unpkg.com/docsify-mermaid@latest/dist/docsify-mermaid.js"></script>
```

I'm left this as an issue; this is a tiny thing. Thanks

**Comment by Leward** [comment]
I accepted https://github.com/Leward/mermaid-docsify/pull/17 which just does that.
