### ISSUE TITLE
An inspiration

### ISSUE THREAD

**Issue by aajiwani** [Leward/mermaid-docsify#5]
Hey Leward,

Thanks for your awesome work with `mermaid-docsify`. I am new to this arena but found your package to be very useful. I am currently using it in one of my projects and created my own docsify plugin based on your work.

It would be my pleasure if you visit my work [here](https://github.com/aajiwani/websequencediagrams-docsify/tree/feature/pipeline)

Thanks.

Keep up the awesomeness!

**Comment by Leward** [comment]
Hello Amir, thank you for your kind words :pray:
